version: '3.8'

services:
  xmltv:
    image: mrorbitman/schedules-direct-update-and-serve:latest
    environment:
      - SD_USERNAME=${SCHEDULES_DIRECT_USERNAME}
      - SD_PASSWORD=${SCHEDULES_DIRECT_PASSWORD}
      - SD_LINEUPS=USA-0000001-CUSTOM,USA-DITV505-X,USA-MI21464-X,USA-YOUTUBE-X
      - TZ=America/New_York
    container_name: xmltv
    ports:
      - "51969:80"
    volumes:
      - xmltv_data:/var/www/html
    restart: unless-stopped

volumes:
  xmltv_data:
